services:
  - type: web
    name: multiverse-gamer-backend
    env: python
    plan: free
    buildCommand: poetry install --no-interaction --no-ansi
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    region: oregon
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.1
      - key: PIP_NO_CACHE_DIR
        value: "off"
      - key: PORT
        fromService:
          name: multiverse-gamer-backend
          type: web
        value: "10000"
